package com.deakin.llm_quiz_app

import android.content.Intent
import android.graphics.Typeface
import android.os.Bundle
import android.util.TypedValue
import android.widget.Button
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import com.deakin.llm_quiz_app.data.DatabaseHelper

class HomeActivity : AppCompatActivity() {
    fun String.title() = replaceFirstChar(Char::titlecase)
    var userId: Int = -1

    fun createQuestionDiv(interest: String): LinearLayout {
        // Step 2: Create a new LinearLayout (the "question_div" container)
        val questionDiv = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(50, 50, 50, 50)
            setBackgroundResource(R.drawable.question_div)
            isClickable = true
            isFocusable = true

            val params = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            )
            params.setMargins(0, 0, 0, 20)
            layoutParams = params
        }

        // Step 3: Create TextViews and add them to the container
        val titleText = TextView(this).apply {
            text = "${interest.title()} Quiz"
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 20f)
            setTypeface(null, Typeface.BOLD)
            setTextColor(ContextCompat.getColor(context, R.color.white))
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            )
        }

        val subtitleText = TextView(this).apply {
            text = "- Generated by AI"
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 15f)
            setTextColor(ContextCompat.getColor(context, R.color.white))
            val params = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            )
            params.topMargin = 10
            layoutParams = params
        }

        // Step 4: Add TextViews to the new container
        questionDiv.addView(titleText)
        questionDiv.addView(subtitleText)

        questionDiv.setOnClickListener {
            val loadQuizIntent = Intent(this, LoadQuizActivity::class.java)
            loadQuizIntent.putExtra("topic", interest)
            loadQuizIntent.putExtra("userId", userId)
            startActivity(loadQuizIntent)
        }

        return questionDiv
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_home)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        val db = DatabaseHelper(this, null)
        userId = intent.getIntExtra("userId", -1)
        val interests = db.getUserInterests(userId)

        if (userId == -1) {
            val homeIntent = Intent(this, HomeActivity::class.java)
            Toast.makeText(this, "Invalid user ID", Toast.LENGTH_LONG).show()
            startActivity(homeIntent)
        }

        val usernameText = findViewById<TextView>(R.id.usernameText)
        usernameText.text = db.getUsername(userId).title()

        val btnInterests = findViewById<Button>(R.id.btnInterests)

        btnInterests.setOnClickListener {
            val interestsIntent = Intent(this, InterestsActivity::class.java)
            interestsIntent.putExtra("userId", userId)
            startActivity(interestsIntent)
        }

        val quizzesLayout = findViewById<LinearLayout>(R.id.quizzes)

        // Step 1: Clear existing views
         quizzesLayout.removeAllViews()

        for (interest in interests) {
            quizzesLayout.addView(createQuestionDiv(interest))
        }
    }
}